version: '3'
services:
  proxy:
    build: .
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
  backend:
    image: your-backend-image  # Replace with your backend image
    ports:
      - "port:port"  # Replace with the necessary ports
